#!/usr/bin/env python3
# zote_correlation_v3.py
# Run from ~/Desktop/ZOTE/
# Clean rewrite of correlation.cpp

import pathlib

cpp = []
cpp.append("// src/correlation.cpp")
cpp.append("// ZOTE — zenithcpp Open Source Threat Engine")
cpp.append("// ISO C++23 compliant — zero external dependencies")
cpp.append("// Apache 2.0 License — https://github.com/zenithcpp/zote")
cpp.append("")
cpp.append("#include <zote/correlation.hpp>")
cpp.append("#include <optional>")
cpp.append("")
cpp.append("#include <algorithm>")
cpp.append("#include <atomic>")
cpp.append("#include <chrono>")
cpp.append("#include <memory>")
cpp.append("#include <mutex>")
cpp.append("#include <string>")
cpp.append("#include <unordered_map>")
cpp.append("#include <vector>")
cpp.append("")
cpp.append("namespace zote {")
cpp.append("")
cpp.append("static std::uint64_t now_us() noexcept {")
cpp.append("    return static_cast<std::uint64_t>(")
cpp.append("        std::chrono::duration_cast<std::chrono::microseconds>(")
cpp.append("            std::chrono::steady_clock::now()")
cpp.append("                .time_since_epoch()).count());")
cpp.append("}")
cpp.append("")
cpp.append("// ─── Actor attribution table ─────────────────────────────────────────────")
cpp.append("struct ActorSig {")
cpp.append("    const char* mitre_id;")
cpp.append("    const char* actor;")
cpp.append("};")
cpp.append("static constexpr ActorSig ACTOR_SIGS[] = {")
cpp.append('    {"T1566", "APT28"},')
cpp.append('    {"T1059", "APT29"},')
cpp.append('    {"T1486", "LockBit"},')
cpp.append('    {"T1190", "APT41"},')
cpp.append('    {"T1003", "Lazarus"},')
cpp.append('    {"T1021", "Cobalt"},')
cpp.append('    {"T1055", "FIN7"},')
cpp.append('    {"T1485", "Sandworm"},')
cpp.append('    {"T1490", "WizardSpider"},')
cpp.append('    {"T1558", "APT29"},')
cpp.append('    {"T1550", "APT28"},')
cpp.append('    {"T1071", "Cobalt"},')
cpp.append("};")
cpp.append("static constexpr std::size_t ACTOR_SIG_COUNT =")
cpp.append("    sizeof(ACTOR_SIGS)/sizeof(ACTOR_SIGS[0]);")
cpp.append("")
cpp.append("// ─── Impl ────────────────────────────────────────────────────────────────")
cpp.append("struct CorrelationEngine::Impl {")
cpp.append("    std::vector<CorrelatedAlert>                          alerts;")
cpp.append("    std::vector<Campaign>                                 campaigns;")
cpp.append("    std::unordered_map<std::string, UebaProfile>          ueba;")
cpp.append("    std::unordered_map<std::string, std::uint64_t>        ip_campaign_idx;")
cpp.append("    std::atomic<std::uint64_t>                            alert_count{0};")
cpp.append("    std::uint64_t                                         next_campaign_id{1};")
cpp.append("    mutable std::mutex                                    mtx;")
cpp.append("    CorrelationConfig                                     cfg;")
cpp.append("")
cpp.append("    void update_campaign(const CorrelatedAlert& a) noexcept {")
cpp.append("        // O(1) lookup via IP→CampaignId index")
cpp.append("        auto it = ip_campaign_idx.find(a.src_ip.value);")
cpp.append("        if (it != ip_campaign_idx.end()) {")
cpp.append("            for (auto& c : campaigns) {")
cpp.append("                if (c.id.value != it->second) continue;")
cpp.append("                c.last_seen_us = a.timestamp_us;")
cpp.append("                c.alert_count++;")
cpp.append("                c.state = CampaignState::Active;")
cpp.append("                c.risk_score = std::min(10.0f,")
cpp.append("                    c.risk_score + a.risk_score * 0.1f);")
cpp.append("                if (!a.mitre_id.empty()) {")
cpp.append("                    bool found = false;")
cpp.append("                    for (const auto& m : c.mitre_ids)")
cpp.append("                        if (m.value == a.mitre_id.value)")
cpp.append("                            { found = true; break; }")
cpp.append("                    if (!found) c.mitre_ids.push_back(a.mitre_id);")
cpp.append("                }")
cpp.append("                bool sfound = false;")
cpp.append("                for (const auto& s : c.stages)")
cpp.append("                    if (s == a.kill_chain)")
cpp.append("                        { sfound = true; break; }")
cpp.append("                if (!sfound) c.stages.push_back(a.kill_chain);")
cpp.append("                c.timeline.push_back({")
cpp.append("                    a.timestamp_us, a.kill_chain,")
cpp.append("                    a.mitre_id, a.description,")
cpp.append("                    a.src_ip, a.severity")
cpp.append("                });")
cpp.append("                return;")
cpp.append("            }")
cpp.append("        }")
cpp.append("        // New campaign")
cpp.append("        Campaign c;")
cpp.append("        c.id             = CampaignId{next_campaign_id++};")
cpp.append('        c.name           = "Campaign-" +')
cpp.append("                           std::to_string(c.id.value);")
cpp.append("        c.first_seen_us  = a.timestamp_us;")
cpp.append("        c.last_seen_us   = a.timestamp_us;")
cpp.append("        c.risk_score     = a.risk_score;")
cpp.append("        c.alert_count    = 1;")
cpp.append("        c.state          = CampaignState::Active;")
cpp.append("        c.src_ips.push_back(a.src_ip);")
cpp.append("        if (!a.mitre_id.empty())")
cpp.append("            c.mitre_ids.push_back(a.mitre_id);")
cpp.append("        c.stages.push_back(a.kill_chain);")
cpp.append("        c.timeline.push_back({")
cpp.append("            a.timestamp_us, a.kill_chain,")
cpp.append("            a.mitre_id, a.description,")
cpp.append("            a.src_ip, a.severity")
cpp.append("        });")
cpp.append("        ip_campaign_idx[a.src_ip.value] = c.id.value;")
cpp.append("        campaigns.push_back(std::move(c));")
cpp.append("    }")
cpp.append("")
cpp.append("    void update_ueba(const CorrelatedAlert& a) noexcept {")
cpp.append("        auto& p        = ueba[a.src_ip.value];")
cpp.append("        p.ip           = a.src_ip;")
cpp.append("        p.alert_count_24h++;")
cpp.append("        p.last_seen_us = a.timestamp_us;")
cpp.append("        if (!a.dst_ip.empty()) p.unique_dst_count++;")
cpp.append("        p.anomaly_score = std::min(10.0f,")
cpp.append("            static_cast<float>(p.alert_count_24h) * 0.5f);")
cpp.append("        p.is_anomalous = p.anomaly_score >=")
cpp.append("                         cfg.anomaly_threshold;")
cpp.append("    }")
cpp.append("};")
cpp.append("")
cpp.append("// ─── Construction ─────────────────────────────────────────────────────────")
cpp.append("")
cpp.append("CorrelationEngine::CorrelationEngine(")
cpp.append("    CorrelationConfig cfg) noexcept")
cpp.append("    : impl_(std::make_unique<Impl>()) {")
cpp.append("    if (impl_) impl_->cfg = std::move(cfg);")
cpp.append("}")
cpp.append("")
cpp.append("CorrelationEngine::~CorrelationEngine() = default;")
cpp.append("")
cpp.append("CorrelationEngine::CorrelationEngine(")
cpp.append("    CorrelationEngine&&) noexcept = default;")
cpp.append("CorrelationEngine& CorrelationEngine::operator=(")
cpp.append("    CorrelationEngine&&) noexcept = default;")
cpp.append("")
cpp.append("// ─── Ingest ───────────────────────────────────────────────────────────────")
cpp.append("")
cpp.append("void CorrelationEngine::ingest(")
cpp.append("    const CorrelatedAlert& alert) noexcept {")
cpp.append("    if (!impl_) return;")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    auto a = alert;")
cpp.append("    if (a.timestamp_us == 0) a.timestamp_us = now_us();")
cpp.append("    a.kill_chain = map_kill_chain(a).stage;")
cpp.append("    impl_->alerts.push_back(a);")
cpp.append("    impl_->update_campaign(a);")
cpp.append("    impl_->update_ueba(a);")
cpp.append("    ++impl_->alert_count;")
cpp.append("}")
cpp.append("")
cpp.append("// ─── Campaign access ──────────────────────────────────────────────────────")
cpp.append("")
cpp.append("std::vector<Campaign>")
cpp.append("CorrelationEngine::campaigns_snapshot() const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    return impl_->campaigns;")
cpp.append("}")
cpp.append("")
cpp.append("const Campaign* CorrelationEngine::campaign_for_ip(")
cpp.append("    std::string_view ip) const noexcept {")
cpp.append("    if (!impl_) return nullptr;")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    auto it = impl_->ip_campaign_idx.find(std::string(ip));")
cpp.append("    if (it == impl_->ip_campaign_idx.end()) return nullptr;")
cpp.append("    for (const auto& c : impl_->campaigns)")
cpp.append("        if (c.id.value == it->second) return &c;")
cpp.append("    return nullptr;")
cpp.append("}")
cpp.append("")
cpp.append("Campaign* CorrelationEngine::campaign_for_ip_mut(")
cpp.append("    std::string_view ip) noexcept {")
cpp.append("    if (!impl_) return nullptr;")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    auto it = impl_->ip_campaign_idx.find(std::string(ip));")
cpp.append("    if (it == impl_->ip_campaign_idx.end()) return nullptr;")
cpp.append("    for (auto& c : impl_->campaigns)")
cpp.append("        if (c.id.value == it->second) return &c;")
cpp.append("    return nullptr;")
cpp.append("}")
cpp.append("")
cpp.append("float CorrelationEngine::risk_score(")
cpp.append("    std::string_view ip) const noexcept {")
cpp.append("    if (!impl_) return 0.0f;")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    float score = 0.0f;")
cpp.append("    for (const auto& a : impl_->alerts)")
cpp.append("        if (a.src_ip.value == ip)")
cpp.append("            score = std::min(10.0f,")
cpp.append("                score + a.risk_score * 0.2f);")
cpp.append("    return score;")
cpp.append("}")
cpp.append("")
cpp.append("UebaProfile CorrelationEngine::ueba_profile(")
cpp.append("    std::string_view ip) const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    auto it = impl_->ueba.find(std::string(ip));")
cpp.append("    if (it == impl_->ueba.end()) return {};")
cpp.append("    return it->second;")
cpp.append("}")
cpp.append("")
cpp.append("KillChainAssessment CorrelationEngine::map_kill_chain(")
cpp.append("    const CorrelatedAlert& alert) noexcept {")
cpp.append("    Signal sig;")
cpp.append("    sig.description  = alert.description;")
cpp.append("    sig.category_str = alert.category;")
cpp.append("    sig.mitre_id     = alert.mitre_id;")
cpp.append("    return KillChainMapper::assess(sig);")
cpp.append("}")
cpp.append("")
cpp.append("Attribution CorrelationEngine::attribute_actor(")
cpp.append("    CampaignId campaign_id) const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    const Campaign* camp = nullptr;")
cpp.append("    for (const auto& c : impl_->campaigns)")
cpp.append("        if (c.id == campaign_id) { camp = &c; break; }")
cpp.append("    if (!camp) return {};")
cpp.append("    std::unordered_map<std::string, int> scores;")
cpp.append("    std::unordered_map<std::string, std::vector<TechniqueId>> matched;")
cpp.append("    for (const auto& mid : camp->mitre_ids)")
cpp.append("        for (std::size_t i = 0; i < ACTOR_SIG_COUNT; ++i)")
cpp.append("            if (mid.value == ACTOR_SIGS[i].mitre_id) {")
cpp.append("                scores[ACTOR_SIGS[i].actor]++;")
cpp.append("                matched[ACTOR_SIGS[i].actor].push_back(mid);")
cpp.append("            }")
cpp.append("    if (scores.empty()) return {};")
cpp.append("    std::string best; int best_score = 0;")
cpp.append("    for (const auto& [actor, score] : scores)")
cpp.append("        if (score > best_score)")
cpp.append("            { best_score = score; best = actor; }")
cpp.append("    Attribution attr;")
cpp.append("    attr.actor      = ActorId{best};")
cpp.append("    attr.confidence = std::min(1.0f,")
cpp.append("        static_cast<float>(best_score) * 0.2f);")
cpp.append("    attr.matched_techniques = matched[best];")
cpp.append("    return attr;")
cpp.append("}")
cpp.append("")
cpp.append("std::uint64_t CorrelationEngine::alert_count() const noexcept {")
cpp.append("    if (!impl_) return 0;")
cpp.append("    return impl_->alert_count.load();")
cpp.append("}")
cpp.append("")
cpp.append("void CorrelationEngine::submit(")
cpp.append("    const KillChainAssessment& assessment,")
cpp.append("    std::string_view           src_ip,")
cpp.append("    float                      risk_score) noexcept {")
cpp.append("    if (!impl_) return;")
cpp.append("    CorrelatedAlert a;")
cpp.append("    a.src_ip      = IpAddress{std::string(src_ip)};")
cpp.append("    a.kill_chain  = assessment.stage;")
cpp.append("    a.risk_score  = risk_score;")
cpp.append("    a.severity    = Severity::Medium;")
cpp.append("    if (!assessment.reasons.empty())")
cpp.append("        a.description = assessment.reasons[0].field +")
cpp.append('                        ": " + assessment.reasons[0].match;')
cpp.append("    else")
cpp.append("        a.description = KillChainMapper::stage_name(assessment.stage);")
cpp.append("    ingest(a);")
cpp.append("}")
cpp.append("")
cpp.append("void CorrelationEngine::reset() noexcept {")
cpp.append("    if (!impl_) return;")
cpp.append("    std::lock_guard lock(impl_->mtx);")
cpp.append("    impl_->alerts.clear();")
cpp.append("    impl_->campaigns.clear();")
cpp.append("    impl_->ueba.clear();")
cpp.append("    impl_->ip_campaign_idx.clear();")
cpp.append("    impl_->alert_count.store(0);")
cpp.append("    impl_->next_campaign_id = 1;")
cpp.append("}")
cpp.append("")
cpp.append("} // namespace zote")
cpp.append("")

pathlib.Path("src/correlation.cpp").write_text(
    "\n".join(cpp), encoding="utf-8")
print(f"OK -- src/correlation.cpp rewritten clean ({len(cpp)} lines)")
