#!/usr/bin/env python3
# zote_engine_v2.py
# Run from ~/Desktop/ZOTE/
# Updates engine.hpp with review improvements

import pathlib

hpp = []
hpp.append("#pragma once")
hpp.append("// include/zote/engine.hpp")
hpp.append("// ZOTE — zenithcpp Open Source Threat Engine")
hpp.append("// ISO C++23 compliant — zero external dependencies")
hpp.append("// Apache 2.0 License — https://github.com/zenithcpp/zote")
hpp.append("//")
hpp.append("// Detection Runtime Kernel (DRK) — evaluates signals against")
hpp.append("// detection rules with evidence-based confidence scoring.")
hpp.append("//")
hpp.append("// ── Evaluation pipeline (in order) ───────────────────────────────────────")
hpp.append("//")
hpp.append("//   1. Whitelist check      → suppress if IP matches whitelist")
hpp.append("//   2. IP suppression       → suppress if IP is temporarily suppressed")
hpp.append("//   3. Rule suppression     → suppress if rule ID is suppressed")
hpp.append("//   4. FP score filter      → suppress if fp_score >= cfg.fp_threshold")
hpp.append("//   5. Condition evaluation → structured conditions OR legacy pattern")
hpp.append("//   6. Threshold check      → fire only after N matches in window")
hpp.append("//   7. Evidence collection  → which fields triggered the match")
hpp.append("//   8. Confidence scoring   → weighted sum of matched conditions")
hpp.append("//   9. Severity score       → severity enum mapped to 0.0-10.0 float")
hpp.append("//")
hpp.append("// ── Confidence calibration model ─────────────────────────────────────────")
hpp.append("//")
hpp.append("//   Confidence is deterministic: same rule + same signal = same value.")
hpp.append("//   For structured condition rules:")
hpp.append("//     confidence = sum(matched_condition.weight) / sum(all_condition.weight)")
hpp.append("//   For legacy pattern rules (single pattern string):")
hpp.append("//     confidence = 0.80f (fixed — upgrade to conditions for tuning)")
hpp.append("//   For YARA hex rules:")
hpp.append("//     confidence = 0.95f (binary match — high confidence)")
hpp.append("//   For Sigma/Suricata reference rules:")
hpp.append("//     confidence = 0.90f (reference match — high confidence)")
hpp.append("//   For threshold rules:")
hpp.append("//     confidence = 0.85f (count exceeded — high confidence)")
hpp.append("//")
hpp.append("// ── Thread-safety contract ───────────────────────────────────────────────")
hpp.append("//")
hpp.append("//   All public member functions are thread-safe.")
hpp.append("//   Multiple evaluate() calls may run concurrently.")
hpp.append("//   Rule modifications may occur concurrently with evaluation.")
hpp.append("//   Callers observe a consistent snapshot of the active rule set.")
hpp.append("//")
hpp.append("// ── Suppression model ────────────────────────────────────────────────────")
hpp.append("//")
hpp.append("//   IP suppression:   exact string match only (v0.1).")
hpp.append("//                     CIDR expansion planned for v0.2.")
hpp.append("//   Rule suppression: by RuleId, expires after TTL.")
hpp.append("//   Whitelist:        permanent, exact string match.")
hpp.append("//   Priority:         whitelist > IP suppression > rule suppression > FP.")
hpp.append("//   Bounds:           max_suppressed in DetectionEngineConfig.")
hpp.append("//                     Oldest entries evicted when limit reached.")
hpp.append("//")
hpp.append("// ── v0.1 limitations (documented upgrade path) ───────────────────────────")
hpp.append("//")
hpp.append("//   Rules are interpreted at evaluation time O(n) per signal.")
hpp.append("//   v0.2: CompiledRule + RuleIndex for O(1) field-indexed dispatch.")
hpp.append("//   v0.2: SigmaParser and SuricataParser as separate classes.")
hpp.append("//   v0.2: Sliding window engine for time-series detection.")
hpp.append("//   v1.0: Parallel batch ingestion pipeline.")
hpp.append("//")
hpp.append("#include <zote/types.hpp>")
hpp.append("#include <chrono>")
hpp.append("#include <memory>")
hpp.append("#include <optional>")
hpp.append("#include <span>")
hpp.append("#include <string>")
hpp.append("#include <string_view>")
hpp.append("#include <vector>")
hpp.append("")
hpp.append("namespace zote {")
hpp.append("")
hpp.append("class DetectionEngine {")
hpp.append("public:")
hpp.append("    // Config applied at construction.")
hpp.append("    // Use DetectionEngineConfig{} for all defaults.")
hpp.append("    explicit DetectionEngine(")
hpp.append("        DetectionEngineConfig cfg = {}) noexcept;")
hpp.append("")
hpp.append("    ~DetectionEngine();")
hpp.append("")
hpp.append("    // Not copyable — use move semantics or shared_ptr.")
hpp.append("    DetectionEngine(const DetectionEngine&)            = delete;")
hpp.append("    DetectionEngine& operator=(const DetectionEngine&) = delete;")
hpp.append("")
hpp.append("    DetectionEngine(DetectionEngine&&) noexcept;")
hpp.append("    DetectionEngine& operator=(DetectionEngine&&) noexcept;")
hpp.append("")
hpp.append("    // ── Rule management ───────────────────────────────────────────────")
hpp.append("")
hpp.append("    // Add or replace a rule (replaces if ID already exists).")
hpp.append("    void add_rule(const DetectionRule& rule) noexcept;")
hpp.append("")
hpp.append("    // Add multiple rules in a single lock acquisition.")
hpp.append("    // Preferred over repeated add_rule() for bulk loading.")
hpp.append("    void add_rules(std::span<const DetectionRule> rules) noexcept;")
hpp.append("")
hpp.append("    // Remove rule by ID. No-op if not found.")
hpp.append("    void remove_rule(RuleId rule_id) noexcept;")
hpp.append("")
hpp.append("    // Enable or disable a rule without removing it.")
hpp.append("    void set_rule_enabled(RuleId rule_id, bool enabled) noexcept;")
hpp.append("")
hpp.append("    // Set false positive score (0.0-1.0).")
hpp.append("    // Rule suppressed when fp_score >= cfg.fp_threshold.")
hpp.append("    void set_fp_score(RuleId rule_id, float score) noexcept;")
hpp.append("")
hpp.append("    // Set count/window threshold for a rule.")
hpp.append("    // Rule fires only after count matches within window_sec.")
hpp.append("    void set_threshold(RuleId        rule_id,")
hpp.append("                       std::uint32_t count,")
hpp.append("                       std::uint32_t window_sec) noexcept;")
hpp.append("")
hpp.append("    // ── Rule queries ──────────────────────────────────────────────────")
hpp.append("")
hpp.append("    [[nodiscard]] bool")
hpp.append("    has_rule(RuleId rule_id) const noexcept;")
hpp.append("")
hpp.append("    [[nodiscard]] std::optional<DetectionRule>")
hpp.append("    get_rule(RuleId rule_id) const noexcept;")
hpp.append("")
hpp.append("    // ── Suppression ───────────────────────────────────────────────────")
hpp.append("")
hpp.append("    // Suppress all alerts from an IP for the given duration.")
hpp.append("    // Note: exact string match only in v0.1. CIDR in v0.2.")
hpp.append("    // Evicts oldest entry if max_suppressed limit reached.")
hpp.append("    void suppress_ip(std::string_view     ip,")
hpp.append("                     std::chrono::seconds ttl) noexcept;")
hpp.append("")
hpp.append("    // Suppress a specific rule for the given duration.")
hpp.append("    void suppress_rule(RuleId               rule_id,")
hpp.append("                       std::chrono::seconds ttl) noexcept;")
hpp.append("")
hpp.append("    // Add IP or CIDR string to permanent whitelist.")
hpp.append("    // Whitelist takes priority over all suppression.")
hpp.append("    void whitelist_add(std::string_view ip_or_cidr) noexcept;")
hpp.append("")
hpp.append("    // Remove from whitelist.")
hpp.append("    void whitelist_remove(std::string_view ip_or_cidr) noexcept;")
hpp.append("")
hpp.append("    // Check if IP matches whitelist.")
hpp.append("    [[nodiscard]] bool")
hpp.append("    is_whitelisted(std::string_view ip) const noexcept;")
hpp.append("")
hpp.append("    // ── Evaluation ────────────────────────────────────────────────────")
hpp.append("")
hpp.append("    // Vector API — usability-oriented.")
hpp.append("    // Returns only matched results.")
hpp.append("    // Allocates result vector on heap — use callback API for")
hpp.append("    // high-throughput streaming pipelines.")
hpp.append("    [[nodiscard]] std::vector<DetectionResult>")
hpp.append("    evaluate(const Signal& signal) noexcept;")
hpp.append("")
hpp.append("    // Callback API — streaming-oriented, zero heap allocation.")
hpp.append("    // Calls cb for each matched result immediately.")
hpp.append("    // Preferred for high-throughput SOC pipelines (>100k EPS).")
hpp.append("    void evaluate(const Signal&  signal,")
hpp.append("                  AlertCallback  cb) noexcept;")
hpp.append("")
hpp.append("    // Batch evaluation — evaluates multiple signals.")
hpp.append("    // Returns all matched results across all signals.")
hpp.append("    [[nodiscard]] std::vector<DetectionResult>")
hpp.append("    evaluate_batch(std::span<const Signal> signals) noexcept;")
hpp.append("")
hpp.append("    // Batch evaluation with callback — streaming batch.")
hpp.append("    void evaluate_batch(std::span<const Signal> signals,")
hpp.append("                        AlertCallback           cb) noexcept;")
hpp.append("")
hpp.append("    // Test a single rule — no counters incremented, no callbacks.")
hpp.append("    // Returns nullopt if rule does not match signal.")
hpp.append("    // Confidence and evidence ARE populated on match.")
hpp.append("    [[nodiscard]] std::optional<DetectionResult>")
hpp.append("    test_rule(const DetectionRule& rule,")
hpp.append("              const Signal&        signal) const noexcept;")
hpp.append("")
hpp.append("    // ── Rule loading ──────────────────────────────────────────────────")
hpp.append("    //")
hpp.append("    // Note: These functions couple loading to the engine.")
hpp.append("    // v0.2 will introduce SigmaParser and SuricataParser")
hpp.append("    // as separate classes for cleaner architecture.")
hpp.append("    // These convenience functions will remain as wrappers.")
hpp.append("")
hpp.append("    // Load Suricata .rules file.")
hpp.append("    // Returns count of rules loaded.")
hpp.append("    // Does not throw — returns 0 on file open failure.")
hpp.append("    [[nodiscard]] std::size_t")
hpp.append("    load_suricata_rules(const std::string& path);")
hpp.append("")
hpp.append("    // Load directory of Sigma .yml files.")
hpp.append("    // Returns count of rules loaded.")
hpp.append("    // Does not throw — returns 0 on directory open failure.")
hpp.append("    [[nodiscard]] std::size_t")
hpp.append("    load_sigma_rules(const std::string& directory);")
hpp.append("")
hpp.append("    // Add a hex byte pattern rule (YARA-like).")
hpp.append("    // Pattern format: \"4D 5A 90 00\" (space-separated hex bytes).")
hpp.append("    // Matches against signal.raw field only.")
hpp.append("    // Not full YARA language — hex byte matching only in v0.1.")
hpp.append("    void add_yara_rule(const std::string& name,")
hpp.append("                       const std::string& hex_pattern,")
hpp.append("                       Severity           severity) noexcept;")
hpp.append("")
hpp.append("    // ── Stats and observability ───────────────────────────────────────")
hpp.append("")
hpp.append("    [[nodiscard]] std::size_t   rule_count()  const noexcept;")
hpp.append("    [[nodiscard]] std::uint64_t alert_count() const noexcept;")
hpp.append("    [[nodiscard]] EngineStats   stats()       const noexcept;")
hpp.append("")
hpp.append("    // Reset runtime state (counters, suppression, thresholds).")
hpp.append("    // Rules remain loaded. Call before replaying events.")
hpp.append("    void reset() noexcept;")
hpp.append("")
hpp.append("    // Clear all rules and runtime state.")
hpp.append("    void clear() noexcept;")
hpp.append("")
hpp.append("private:")
hpp.append("    struct Impl;")
hpp.append("    std::unique_ptr<Impl> impl_;")
hpp.append("};")
hpp.append("")
hpp.append("} // namespace zote")
hpp.append("")

pathlib.Path("include/zote/engine.hpp").write_text(
    "\n".join(hpp), encoding="utf-8")
print(f"OK -- include/zote/engine.hpp written ({len(hpp)} lines)")

# Update engine.cpp to add callback + batch overloads
path = pathlib.Path("src/engine.cpp")
content = path.read_text()

# Add callback evaluate after vector evaluate
old = "std::optional<DetectionResult>\nDetectionEngine::test_rule("
new = """void DetectionEngine::evaluate(
    const Signal& signal,
    AlertCallback cb) noexcept {
    if (!impl_ || !cb) return;
    auto results = evaluate(signal);
    for (const auto& r : results)
        cb(r);
}

std::vector<DetectionResult>
DetectionEngine::evaluate_batch(
    std::span<const Signal> signals) noexcept {
    std::vector<DetectionResult> all;
    for (const auto& sig : signals) {
        auto r = evaluate(sig);
        for (auto& res : r)
            all.push_back(std::move(res));
    }
    return all;
}

void DetectionEngine::evaluate_batch(
    std::span<const Signal> signals,
    AlertCallback           cb) noexcept {
    if (!cb) return;
    for (const auto& sig : signals)
        evaluate(sig, cb);
}

std::optional<DetectionResult>
DetectionEngine::test_rule("""

content = content.replace(
    "std::optional<DetectionResult>\nDetectionEngine::test_rule(",
    new
)
path.write_text(content)
print("OK -- src/engine.cpp: callback + batch overloads added")
