#!/usr/bin/env python3
# zote_pass4_zote_engine.py
# Run from ~/Desktop/ZOTE/
# Pass 4: ZoteEngine orchestrator — product interface

import pathlib

# ── include/zote/zote_engine.hpp ─────────────────────────────────────────
hpp = []
hpp.append("#pragma once")
hpp.append("// include/zote/zote_engine.hpp")
hpp.append("// ZOTE — zenithcpp Open Source Threat Engine")
hpp.append("// ISO C++23 compliant — zero external dependencies")
hpp.append("// Apache 2.0 License — https://github.com/zenithcpp/zote")
hpp.append("//")
hpp.append("// ZoteEngine — unified product interface.")
hpp.append("//")
hpp.append("// This is the primary entry point for ZOTE.")
hpp.append("// Wires DetectionEngine + KillChainMapper +")
hpp.append("// CorrelationEngine into a single deterministic pipeline:")
hpp.append("//")
hpp.append("//   Signal")
hpp.append("//     ↓  Step 1: DetectionEngine::evaluate()")
hpp.append("//   DetectionResult{confidence, evidence, kill_chain}")
hpp.append("//     ↓  Step 2: KillChainMapper::assess()")
hpp.append("//   KillChainAssessment{stage, candidates, reasons}")
hpp.append("//     ↓  Step 3: ConfidenceNormalizer::combine()")
hpp.append("//   combined_confidence")
hpp.append("//     ↓  Step 4: CorrelationEngine::ingest()")
hpp.append("//   Campaign{timeline, attribution, UEBA}")
hpp.append("//     ↓  Step 5: ThreatAssessment assembly")
hpp.append("//   ThreatAssessment{risk, attribution, kill_chain,")
hpp.append("//                    coverage, timeline, recommendations}")
hpp.append("//")
hpp.append("// ── Basic usage ──────────────────────────────────────────────────────────")
hpp.append("//")
hpp.append("//   zote::ZoteEngine engine;")
hpp.append("//")
hpp.append("//   zote::DetectionRule rule;")
hpp.append("//   rule.id = zote::RuleId{1};")
hpp.append("//   rule.pattern = \"ransomware\";")
hpp.append("//   rule.severity = zote::Severity::Critical;")
hpp.append("//   engine.add_rule(rule);")
hpp.append("//")
hpp.append("//   zote::Signal sig;")
hpp.append("//   sig.net.src = zote::IpAddress{\"1.2.3.4\"};")
hpp.append("//   sig.description = \"ransomware encrypting files\";")
hpp.append("//")
hpp.append("//   auto assessment = engine.process(sig);")
hpp.append("//   // assessment.risk.score — overall risk 0-10")
hpp.append("//   // assessment.attribution.actor — attributed threat actor")
hpp.append("//   // assessment.kill_chain.stage — kill chain stage")
hpp.append("//")
hpp.append("// ── Thread-safety ────────────────────────────────────────────────────────")
hpp.append("//")
hpp.append("//   process() is thread-safe — multiple threads may call concurrently.")
hpp.append("//   add_rule() / configure() serialize with process().")
hpp.append("")
hpp.append("#include <zote/engine.hpp>")
hpp.append("#include <zote/killchain.hpp>")
hpp.append("#include <zote/correlation.hpp>")
hpp.append("#include <zote/mitre.hpp>")
hpp.append("#include <memory>")
hpp.append("#include <span>")
hpp.append("#include <string_view>")
hpp.append("#include <vector>")
hpp.append("")
hpp.append("namespace zote {")
hpp.append("")
hpp.append("// ─── ZoteEngine ──────────────────────────────────────────────────────────")
hpp.append("class ZoteEngine {")
hpp.append("public:")
hpp.append("    // Construct with default configuration.")
hpp.append("    ZoteEngine() noexcept;")
hpp.append("")
hpp.append("    // Construct with custom engine configs.")
hpp.append("    explicit ZoteEngine(DetectionEngineConfig  det_cfg,")
hpp.append("                        CorrelationConfig      corr_cfg = {}) noexcept;")
hpp.append("")
hpp.append("    ~ZoteEngine();")
hpp.append("")
hpp.append("    ZoteEngine(const ZoteEngine&)            = delete;")
hpp.append("    ZoteEngine& operator=(const ZoteEngine&) = delete;")
hpp.append("")
hpp.append("    ZoteEngine(ZoteEngine&&) noexcept;")
hpp.append("    ZoteEngine& operator=(ZoteEngine&&) noexcept;")
hpp.append("")
hpp.append("    // ── Rule management ───────────────────────────────────────────────")
hpp.append("")
hpp.append("    void add_rule(const DetectionRule& rule) noexcept;")
hpp.append("    void add_rules(std::span<const DetectionRule> rules) noexcept;")
hpp.append("    void remove_rule(RuleId rule_id) noexcept;")
hpp.append("    void set_rule_enabled(RuleId rule_id, bool enabled) noexcept;")
hpp.append("    void whitelist_add(std::string_view ip) noexcept;")
hpp.append("    void whitelist_remove(std::string_view ip) noexcept;")
hpp.append("    void suppress_ip(std::string_view ip,")
hpp.append("                     std::chrono::seconds ttl) noexcept;")
hpp.append("")
hpp.append("    // ── Signal processing ─────────────────────────────────────────────")
hpp.append("")
hpp.append("    // Process a single signal through the full pipeline.")
hpp.append("    // Returns ThreatAssessment — unified view of all engine outputs.")
hpp.append("    // Thread-safe — multiple threads may call concurrently.")
hpp.append("    [[nodiscard]] ThreatAssessment")
hpp.append("    process(const Signal& signal) noexcept;")
hpp.append("")
hpp.append("    // Process with callback — fires for each matched detection.")
hpp.append("    // Callback called before correlation for low-latency alerting.")
hpp.append("    void process(const Signal&  signal,")
hpp.append("                 AlertCallback  on_detection) noexcept;")
hpp.append("")
hpp.append("    // Batch processing.")
hpp.append("    [[nodiscard]] std::vector<ThreatAssessment>")
hpp.append("    process_batch(std::span<const Signal> signals) noexcept;")
hpp.append("")
hpp.append("    // ── Campaign access ───────────────────────────────────────────────")
hpp.append("")
hpp.append("    // Safe snapshot of all campaigns.")
hpp.append("    [[nodiscard]] std::vector<Campaign>")
hpp.append("    campaigns_snapshot() const noexcept;")
hpp.append("")
hpp.append("    // Read-only campaign view for an IP.")
hpp.append("    [[nodiscard]] const Campaign*")
hpp.append("    campaign_for_ip(std::string_view ip) const noexcept;")
hpp.append("")
hpp.append("    // ── Intelligence queries ──────────────────────────────────────────")
hpp.append("")
hpp.append("    // Attribute a campaign to a known threat actor.")
hpp.append("    [[nodiscard]] Attribution")
hpp.append("    attribute_actor(CampaignId campaign_id) const noexcept;")
hpp.append("")
hpp.append("    // D3FEND countermeasures for a technique.")
hpp.append("    [[nodiscard]] static std::vector<std::string>")
hpp.append("    countermeasures_for(const TechniqueId& tid);")
hpp.append("")
hpp.append("    // ── Stats and observability ───────────────────────────────────────")
hpp.append("")
hpp.append("    [[nodiscard]] EngineStats   detection_stats() const noexcept;")
hpp.append("    [[nodiscard]] std::size_t   rule_count()      const noexcept;")
hpp.append("    [[nodiscard]] std::size_t   campaign_count()  const noexcept;")
hpp.append("")
hpp.append("    // Reset all runtime state. Rules remain loaded.")
hpp.append("    void reset() noexcept;")
hpp.append("")
hpp.append("    // ── Direct engine access ──────────────────────────────────────────")
hpp.append("    // For advanced use cases requiring direct engine access.")
hpp.append("")
hpp.append("    [[nodiscard]] DetectionEngine&   detection_engine() noexcept;")
hpp.append("    [[nodiscard]] CorrelationEngine& correlation_engine() noexcept;")
hpp.append("")
hpp.append("private:")
hpp.append("    struct Impl;")
hpp.append("    std::unique_ptr<Impl> impl_;")
hpp.append("};")
hpp.append("")
hpp.append("} // namespace zote")
hpp.append("")

pathlib.Path("include/zote/zote_engine.hpp").write_text(
    "\n".join(hpp), encoding="utf-8")
print(f"OK -- include/zote/zote_engine.hpp written ({len(hpp)} lines)")

# ── src/zote_engine.cpp ───────────────────────────────────────────────────
cpp = []
cpp.append("// src/zote_engine.cpp")
cpp.append("// ZOTE — zenithcpp Open Source Threat Engine")
cpp.append("// ISO C++23 compliant — zero external dependencies")
cpp.append("// Apache 2.0 License — https://github.com/zenithcpp/zote")
cpp.append("")
cpp.append("#include <zote/zote_engine.hpp>")
cpp.append("#include <chrono>")
cpp.append("#include <memory>")
cpp.append("#include <vector>")
cpp.append("")
cpp.append("namespace zote {")
cpp.append("")
cpp.append("// ─── Impl ────────────────────────────────────────────────────────────────")
cpp.append("struct ZoteEngine::Impl {")
cpp.append("    DetectionEngine   det;")
cpp.append("    CorrelationEngine corr;")
cpp.append("    ConfidenceModel   conf_model = DEFAULT_CONFIDENCE_MODEL;")
cpp.append("")
cpp.append("    explicit Impl(DetectionEngineConfig  det_cfg,")
cpp.append("                  CorrelationConfig      corr_cfg) noexcept")
cpp.append("        : det(std::move(det_cfg))")
cpp.append("        , corr(std::move(corr_cfg)) {}")
cpp.append("};")
cpp.append("")
cpp.append("// ─── Construction ────────────────────────────────────────────────────────")
cpp.append("")
cpp.append("ZoteEngine::ZoteEngine() noexcept")
cpp.append("    : impl_(std::make_unique<Impl>(")
cpp.append("        DetectionEngineConfig{}, CorrelationConfig{})) {}")
cpp.append("")
cpp.append("ZoteEngine::ZoteEngine(")
cpp.append("    DetectionEngineConfig det_cfg,")
cpp.append("    CorrelationConfig     corr_cfg) noexcept")
cpp.append("    : impl_(std::make_unique<Impl>(")
cpp.append("        std::move(det_cfg), std::move(corr_cfg))) {}")
cpp.append("")
cpp.append("ZoteEngine::~ZoteEngine() = default;")
cpp.append("ZoteEngine::ZoteEngine(ZoteEngine&&) noexcept = default;")
cpp.append("ZoteEngine& ZoteEngine::operator=(ZoteEngine&&) noexcept = default;")
cpp.append("")
cpp.append("// ─── Rule management ─────────────────────────────────────────────────────")
cpp.append("")
cpp.append("void ZoteEngine::add_rule(")
cpp.append("    const DetectionRule& rule) noexcept {")
cpp.append("    if (impl_) impl_->det.add_rule(rule);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::add_rules(")
cpp.append("    std::span<const DetectionRule> rules) noexcept {")
cpp.append("    if (impl_) impl_->det.add_rules(rules);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::remove_rule(RuleId rule_id) noexcept {")
cpp.append("    if (impl_) impl_->det.remove_rule(rule_id);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::set_rule_enabled(")
cpp.append("    RuleId rule_id, bool enabled) noexcept {")
cpp.append("    if (impl_) impl_->det.set_rule_enabled(rule_id, enabled);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::whitelist_add(std::string_view ip) noexcept {")
cpp.append("    if (impl_) impl_->det.whitelist_add(ip);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::whitelist_remove(std::string_view ip) noexcept {")
cpp.append("    if (impl_) impl_->det.whitelist_remove(ip);")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::suppress_ip(")
cpp.append("    std::string_view     ip,")
cpp.append("    std::chrono::seconds ttl) noexcept {")
cpp.append("    if (impl_) impl_->det.suppress_ip(ip, ttl);")
cpp.append("}")
cpp.append("")
cpp.append("// ─── Signal processing ───────────────────────────────────────────────────")
cpp.append("")
cpp.append("ThreatAssessment ZoteEngine::process(")
cpp.append("    const Signal& signal) noexcept {")
cpp.append("    ThreatAssessment assessment;")
cpp.append("    if (!impl_) return assessment;")
cpp.append("")
cpp.append("    // Step 1: Detection engine")
cpp.append("    auto det_results = impl_->det.evaluate(signal);")
cpp.append("")
cpp.append("    // Step 2: Kill chain assessment")
cpp.append("    auto kc = KillChainMapper::assess(signal);")
cpp.append("    assessment.kill_chain.furthest_stage = kc.stage;")
cpp.append("    if (kc.stage != KillChainStage::Unknown)")
cpp.append("        assessment.kill_chain.observed_stages.push_back(kc.stage);")
cpp.append("")
cpp.append("    // Step 3: Build risk from detection results")
cpp.append("    float det_conf   = 0.0f;")
cpp.append("    float risk_score = 0.0f;")
cpp.append("    for (const auto& r : det_results) {")
cpp.append("        if (r.confidence > det_conf) det_conf = r.confidence;")
cpp.append("        if (r.severity_score > risk_score)")
cpp.append("            risk_score = r.severity_score;")
cpp.append("        assessment.risk.evidence.push_back(r);")
cpp.append("    }")
cpp.append("")
cpp.append("    // Step 4: Normalize confidence")
cpp.append("    float combined = impl_->conf_model.apply(")
cpp.append("        det_conf, 0.0f, kc.confidence);")
cpp.append("    assessment.risk.score      = risk_score;")
cpp.append("    assessment.risk.confidence = combined;")
cpp.append("")
cpp.append("    // Step 5: Correlation ingestion")
cpp.append("    if (!det_results.empty()) {")
cpp.append("        CorrelatedAlert ca;")
cpp.append("        ca.src_ip      = signal.net.src;")
cpp.append("        ca.dst_ip      = signal.net.dst;")
cpp.append("        ca.mitre_id    = det_results[0].mitre_id;")
cpp.append("        ca.kill_chain  = kc.stage;")
cpp.append("        ca.risk_score  = risk_score;")
cpp.append("        ca.severity    = det_results[0].severity;")
cpp.append("        ca.description = signal.description;")
cpp.append("        impl_->corr.ingest(ca);")
cpp.append("    }")
cpp.append("")
cpp.append("    // Step 6: Attribution")
cpp.append("    if (!signal.net.src.empty()) {")
cpp.append("        auto* camp = impl_->corr.campaign_for_ip(")
cpp.append("            signal.net.src.value);")
cpp.append("        if (camp) {")
cpp.append("            assessment.attribution =")
cpp.append("                impl_->corr.attribute_actor(camp->id);")
cpp.append("            assessment.timeline    = camp->timeline;")
cpp.append("            // Kill chain progress")
cpp.append("            assessment.kill_chain.observed_stages =")
cpp.append("                camp->stages;")
cpp.append("            if (!camp->stages.empty()) {")
cpp.append("                assessment.kill_chain.furthest_stage =")
cpp.append("                    camp->stages.back();")
cpp.append("                assessment.kill_chain.completion =")
cpp.append("                    static_cast<float>(camp->stages.size())")
cpp.append("                    / 7.0f; // 7 kill chain stages")
cpp.append("            }")
cpp.append("        }")
cpp.append("    }")
cpp.append("")
cpp.append("    // Step 7: Recommendations")
cpp.append("    if (risk_score >= 8.0f)")
cpp.append('        assessment.recommendations.push_back(')
cpp.append('            "Isolate host immediately");')
cpp.append("    if (kc.stage == KillChainStage::CommandControl)")
cpp.append('        assessment.recommendations.push_back(')
cpp.append('            "Block outbound C2 communication");')
cpp.append("    if (kc.stage == KillChainStage::ActionsOnObj)")
cpp.append('        assessment.recommendations.push_back(')
cpp.append('            "Activate incident response plan");')
cpp.append("")
cpp.append("    return assessment;")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::process(")
cpp.append("    const Signal&  signal,")
cpp.append("    AlertCallback  on_detection) noexcept {")
cpp.append("    if (!impl_) return;")
cpp.append("    impl_->det.evaluate(signal, on_detection);")
cpp.append("    // Also run full pipeline for correlation")
cpp.append("    auto kc = KillChainMapper::assess(signal);")
cpp.append("    CorrelatedAlert ca;")
cpp.append("    ca.src_ip      = signal.net.src;")
cpp.append("    ca.kill_chain  = kc.stage;")
cpp.append("    ca.risk_score  = 5.0f;")
cpp.append("    ca.description = signal.description;")
cpp.append("    impl_->corr.ingest(ca);")
cpp.append("}")
cpp.append("")
cpp.append("std::vector<ThreatAssessment>")
cpp.append("ZoteEngine::process_batch(")
cpp.append("    std::span<const Signal> signals) noexcept {")
cpp.append("    std::vector<ThreatAssessment> results;")
cpp.append("    results.reserve(signals.size());")
cpp.append("    for (const auto& sig : signals)")
cpp.append("        results.push_back(process(sig));")
cpp.append("    return results;")
cpp.append("}")
cpp.append("")
cpp.append("// ─── Campaign access ─────────────────────────────────────────────────────")
cpp.append("")
cpp.append("std::vector<Campaign>")
cpp.append("ZoteEngine::campaigns_snapshot() const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    return impl_->corr.campaigns_snapshot();")
cpp.append("}")
cpp.append("")
cpp.append("const Campaign* ZoteEngine::campaign_for_ip(")
cpp.append("    std::string_view ip) const noexcept {")
cpp.append("    if (!impl_) return nullptr;")
cpp.append("    return impl_->corr.campaign_for_ip(ip);")
cpp.append("}")
cpp.append("")
cpp.append("Attribution ZoteEngine::attribute_actor(")
cpp.append("    CampaignId campaign_id) const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    return impl_->corr.attribute_actor(campaign_id);")
cpp.append("}")
cpp.append("")
cpp.append("std::vector<std::string>")
cpp.append("ZoteEngine::countermeasures_for(")
cpp.append("    const TechniqueId& tid) {")
cpp.append("    return MitreDb::d3fend_for(tid.value);")
cpp.append("}")
cpp.append("")
cpp.append("// ─── Stats ───────────────────────────────────────────────────────────────")
cpp.append("")
cpp.append("EngineStats ZoteEngine::detection_stats() const noexcept {")
cpp.append("    if (!impl_) return {};")
cpp.append("    return impl_->det.stats();")
cpp.append("}")
cpp.append("")
cpp.append("std::size_t ZoteEngine::rule_count() const noexcept {")
cpp.append("    if (!impl_) return 0;")
cpp.append("    return impl_->det.rule_count();")
cpp.append("}")
cpp.append("")
cpp.append("std::size_t ZoteEngine::campaign_count() const noexcept {")
cpp.append("    if (!impl_) return 0;")
cpp.append("    return impl_->corr.campaigns_snapshot().size();")
cpp.append("}")
cpp.append("")
cpp.append("void ZoteEngine::reset() noexcept {")
cpp.append("    if (!impl_) return;")
cpp.append("    impl_->det.reset();")
cpp.append("    impl_->corr.reset();")
cpp.append("}")
cpp.append("")
cpp.append("DetectionEngine& ZoteEngine::detection_engine() noexcept {")
cpp.append("    return impl_->det;")
cpp.append("}")
cpp.append("")
cpp.append("CorrelationEngine& ZoteEngine::correlation_engine() noexcept {")
cpp.append("    return impl_->corr;")
cpp.append("}")
cpp.append("")
cpp.append("} // namespace zote")
cpp.append("")

pathlib.Path("src/zote_engine.cpp").write_text(
    "\n".join(cpp), encoding="utf-8")
print(f"OK -- src/zote_engine.cpp written ({len(cpp)} lines)")
